--
-- ER/Studio 8.0 SQL Code Generation
-- Company :      USAC
-- Project :      practica4-201213230.dm1
-- Author :       JFI
--
-- Date Created : Friday, April 24, 2015 22:33:42
-- Target DBMS : MySQL 5.x
--

-- 
-- TABLE: ASIGNACION 
--

CREATE TABLE ASIGNACION(
    BUS      DECIMAL(10, 0)    NOT NULL,
    FECHA    DATE              NOT NULL,
    RUTA     DECIMAL(10, 0)    NOT NULL,
    PRIMARY KEY (BUS, FECHA, RUTA)
)
;



-- 
-- TABLE: BUS 
--

CREATE TABLE BUS(
    BUS         DECIMAL(10, 0)    NOT NULL,
    TIPO_BUS    DECIMAL(10, 0)    NOT NULL,
    PRIMARY KEY (BUS)
)
;



-- 
-- TABLE: CLIENTE 
--

CREATE TABLE CLIENTE(
    DPI         VARCHAR(20)    NOT NULL,
    NOMBRE      VARCHAR(40)    NOT NULL,
    TELEFONO    VARCHAR(10),
    PRIMARY KEY (DPI)
)
;



-- 
-- TABLE: PARTE 
--

CREATE TABLE PARTE(
    RUTA         DECIMAL(10, 0)    NOT NULL,
    PUNTO        DECIMAL(10, 0)    NOT NULL,
    DISTANCIA    DECIMAL(10, 0)    NOT NULL,
    PRIMARY KEY (RUTA, PUNTO)
)
;



-- 
-- TABLE: PUNTO 
--

CREATE TABLE PUNTO(
    PUNTO     DECIMAL(10, 0)    NOT NULL,
    NOMBRE    VARCHAR(40),
    PRIMARY KEY (PUNTO)
)
;



-- 
-- TABLE: RESERVACION 
--

CREATE TABLE RESERVACION(
    RESERVACION    DECIMAL(10, 0)    NOT NULL,
    FECHA          DATE,
    PAGADA         BIT(1)            NOT NULL,
    TOTAL          DECIMAL(10, 0)    NOT NULL,
    RUTA           DECIMAL(10, 0)    NOT NULL,
    ORIGEN         DECIMAL(10, 0)    NOT NULL,
    DESTINO        DECIMAL(10, 0)    NOT NULL,
    CLIENTE        VARCHAR(20)       NOT NULL,
    PRIMARY KEY (RESERVACION)
)
;



-- 
-- TABLE: RUTA 
--

CREATE TABLE RUTA(
    RUTA      DECIMAL(10, 0)    NOT NULL,
    NOMBRE    VARCHAR(20),
    PRIMARY KEY (RUTA)
)
;



-- 
-- TABLE: TIPO_BUS 
--

CREATE TABLE TIPO_BUS(
    TIPO_BUS     DECIMAL(10, 0)    NOT NULL,
    CAPACIDAD    DECIMAL(10, 0),
    NOMBRE       VARCHAR(20)       NOT NULL,
    PRIMARY KEY (TIPO_BUS)
)
;



-- 
-- TABLE: ASIGNACION 
--

ALTER TABLE ASIGNACION ADD CONSTRAINT RefBUS14 
    FOREIGN KEY (BUS)
    REFERENCES BUS(BUS)
;

ALTER TABLE ASIGNACION ADD CONSTRAINT RefRUTA15 
    FOREIGN KEY (RUTA)
    REFERENCES RUTA(RUTA)
;


-- 
-- TABLE: BUS 
--

ALTER TABLE BUS ADD CONSTRAINT RefTIPO_BUS1 
    FOREIGN KEY (TIPO_BUS)
    REFERENCES TIPO_BUS(TIPO_BUS)
;


-- 
-- TABLE: PARTE 
--

ALTER TABLE PARTE ADD CONSTRAINT RefRUTA9 
    FOREIGN KEY (RUTA)
    REFERENCES RUTA(RUTA)
;

ALTER TABLE PARTE ADD CONSTRAINT RefPUNTO10 
    FOREIGN KEY (PUNTO)
    REFERENCES PUNTO(PUNTO)
;


-- 
-- TABLE: RESERVACION 
--

ALTER TABLE RESERVACION ADD CONSTRAINT RefCLIENTE13 
    FOREIGN KEY (CLIENTE)
    REFERENCES CLIENTE(DPI)
;

ALTER TABLE RESERVACION ADD CONSTRAINT RefPARTE16 
    FOREIGN KEY (RUTA, ORIGEN)
    REFERENCES PARTE(RUTA, PUNTO)
;

ALTER TABLE RESERVACION ADD CONSTRAINT RefPARTE17 
    FOREIGN KEY (RUTA, DESTINO)
    REFERENCES PARTE(RUTA, PUNTO)
;


